login/urls.py
from django.urls import path
from login import views

app_name = 'login'

urlpatterns = [
    path('signup/', views.sign_up, name='sign_up'),
    path('login/', views.login_page, name='login'),
    path('edit/', views.edit_profile, name='edit'),
    path('logout/', views.logout_view, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('user/<username>', views.user, name='user'),
    path('follow/<username>', views.follow, name='follow'),
    path('unfollow/<username>', views.unfollow, name='unfollow')
]

post/urls.py
from django.urls import path
from post import views

app_name = 'posts'

urlpatterns = [
    path('', views.home, name='home'),
    path('liked/<pk>/', views.liked, name='liked'),
    path('unliked/<pk>/', views.unliked, name='unliked'),
]

social/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
from post import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('login.urls')),
    path('post/', include('post.urls')),
    path('', views.home, name='home')
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

login/models.py
from django.db import models
from django.contrib.auth.models import User


class UserProfile(models.Model):
    user = models.OneToOneField(
        User, on_delete=models.CASCADE, related_name='user_profile')
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)
    description = models.TextField(blank=True)
    full_name = models.CharField(max_length=264, blank=True)
    dob = models.DateField(blank=True, null=True)
    website = models.URLField(blank=True)
    facebook = models.URLField(blank=True)


class Follow(models.Model):
    follower = models.ForeignKey(User, on_delete=models.CASCADE, related_name='follower')
    following = models.ForeignKey(User, on_delete=models.CASCADE, related_name='following')
    created_date = models.DateTimeField(auto_now_add=True)
    

login/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from .models import UserProfile

class CreateNewUser(UserCreationForm):
    email = forms.EmailField(required=True, label="", widget=forms.TextInput(
        attrs={'placeholder': 'Email'}))
    username = forms.CharField(required=True, label="", widget=forms.TextInput(
        attrs={'placeholder': 'Username'}))
    password1 = forms.CharField(
        required = True,
        label = "",
        widget = forms.PasswordInput(attrs={'placeholder': 'Password'})
    )
    password2 = forms.CharField(
        required=True,
        label="",
        widget = forms.PasswordInput(attrs={'placeholder': 'Confirm Password'})
    )
    class Meta:
        model = User
        fields = ('email', 'username', 'password1', 'password2')


class EditProfile(forms.ModelForm):
    dob = forms.DateField(widget=forms.TextInput(attrs={'type': 'date'}))
    class Meta:
        model = UserProfile
        exclude = ('user', )

login/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse, reverse_lazy
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User

from .models import UserProfile
from .forms import CreateNewUser, EditProfile
from post.forms import PostForm
from login.models import Follow


def sign_up(request):
    form = CreateNewUser()
    registered = False
    if request.method == 'POST':
        form = CreateNewUser(data=request.POST)
        if form.is_valid():
            user = form.save()
            registered = True
            user_profile = UserProfile(user=user)
            user_profile.save()
            return HttpResponseRedirect(reverse('login:login'))
    context = {
        'title': 'Sign Up',
        'form': form
    }
    return render(request, 'login/signup.html', context=context)


def login_page(request):
    form = AuthenticationForm()
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return HttpResponseRedirect(reverse('posts:home'))
    context = {
        'title': 'Login',
        'form': form,
    }
    return render(request, 'login/login.html', context=context)


@login_required
def edit_profile(request):
    current_user = UserProfile.objects.get(user=request.user)
    form = EditProfile(instance=current_user)

    if request.method == 'POST':
        form = EditProfile(request.POST, request.FILES, instance=current_user)
        if form.is_valid():
            form.save(commit=True)
            form = EditProfile(instance=current_user)
            return HttpResponseRedirect(reverse('login:profile'))
    context={
        'form': form,
        'title': 'Edit Profile'
    }
    return render(request, 'login/profile.html', context=context)


@login_required
def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('login:login'))


@login_required
def profile(request):
    form = PostForm()
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return HttpResponseRedirect(reverse('home'))
    context = {
        'title': 'User',
        'form': form
    }
    return render(request, 'login/user.html', context=context)


@login_required
def user(request, username):
    user = User.objects.get(username=username)
    already_followed = Follow.objects.filter(follower=request.user, following=user)
    if user == request.user:
        return HttpResponseRedirect(reverse('login:profile'))
    context = {
        'title': 'Profile',
        'user_other': user,
        'already_followed': already_followed,
    }
    return render(request, 'login/user_other.html', context=context)


@login_required
def follow(request, username):
    following_user = User.objects.get(username=username)
    follower_user = request.user
    already_followed = Follow.objects.filter(follower=follower_user, following=following_user)
    if not already_followed:
        followed_user = Follow(follower=follower_user, following=following_user)
        followed_user.save()
    return HttpResponseRedirect(reverse('login:user', kwargs={'username':username}))


@login_required
def unfollow(request, username):
    following_user = User.objects.get(username=username)
    follower_user = request.user
    already_followed = Follow.objects.filter(follower=follower_user, following=following_user)
    already_followed.delete()
    return HttpResponseRedirect(reverse('login:user', kwargs={'username': username}))

templates/login/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %}
{{ title }}
{% endblock title_block %}

{% block css_block %}
<style>
    .sign_up {
        width: 550px;
        border: 1px solid #ccc;
        padding: 40px;
    }
    .log_in{
        width: 555px;
        padding: 25px;
        border: 1px solid #ccc;
    }
</style>
{% endblock css_block %}

{% block body_block %}
<center>
<div class="log_in">
    <form action="" method='POST'>
        {{ form|crispy }}
        {% csrf_token %}
        <button type="submit" style="width:100%" class='btn btn-primary'>Log In</button>
    </form>
</div>
<br>
<div class="sign_up">
    <p>Dont have an account? <a href="{% url 'login:sign_up' %}">Sign Up</a></p>
</div>
</center>
{% endblock body_block %}

templates/login/profile.html
{% extends 'navbar.html' %}
{% load crispy_forms_tags %}
{% block title_block %}
    {{ title }}
{% endblock title_block %}

{% block css_block %}
<style>
</style>
{% endblock css_block %}

{% block body_block %}
<div class="">
    <form method='POST' action="" enctype="multipart/form-data">
        {{ form|crispy }}
        {% csrf_token %}
        <button type="submit" name='button' class='btn btn-primary' >Submit</button>
    </form>
</div>
{% endblock body_block %}

templates/login/signup.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %}
    {{ title }}
{% endblock title_block %}

{% block css_block %}
<style>
    .sign_up {
        width: 550px;
        border: 1px solid #ccc;
        padding: 40px;
    }
    .log_in{
        width: 555px;
        padding: 25px;
        border: 1px solid #ccc;
    }
</style>
{% endblock css_block %}

{% block body_block %}
<center>
<div class='sign_up'>
    <h3>Sign up to see photos from your friends</h3>
    <form method="POST">
        {{ form|crispy }}
        {% csrf_token %}
        <button type="submit" style='width:100%' class="btn btn-primary">Sign Up</button>
    </form>
</div>
<br>
<div class="log_in">
    <p>Have an account? <a href="{% url 'login:login' %}">Log In</a></p>
</div>
</center>
{% endblock body_block %}

templates/login/user.html
{% extends 'navbar.html' %}

{% block title_block %}
{{ user.user_profile.full_name }} (@{{user.username}})
{% endblock title_block %}

{% block css_block %}
<style>
    .crop{
        margin-top: 20px;
        width: 200px;
        height: 200px;
        overflow: hidden;
    }
    .crop img{
        width: 400px;
        height: 300px;
        margin: -75px 0 0 -100px;
    }
</style>
{% endblock css_block %}

{% block body_block %}
<div class="row">
    <div class="col-sm-4">
        {% if user.user_profile.profile_pic %}
            <img
                src="/media/{{ user.user_profile.profile_pic }}"
                alt=""
                class="rounded-circle"
                width="150px"
                height="150px"
            />
        {% else %}
            <img
                src="/media/default.png"
                alt=""
                class="rounded-circle"
                width="150px"
                height="150px"
            />
        {% endif %}
    </div>
    <div class="col-sm-8">
        <h3>{{ user.username }} &nbsp; <a href="{% url 'login:edit' %}" class='btn btn-light'>Edit Profile</a></h3>
        <br>
        <h4>{{ user.post.count }} posts &nbsp; &nbsp; 
            {{ user.following.count }} followers &nbsp; &nbsp; 
            {{user.follower.count }} following
        </h4>
        <br>
        <h3>{{ user.user_profile.full_name }}</h3>
        <h6>{{ user.user_profile.description|linebreaks }}</h6>
    </div>
</div>
<button class="btn btn-primary" type='button' data-toggle='modal' data-target='#myModal'>New Post</button>
<div class="modal" id="myModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Post a Photo</h4>
                <button type='button' class='close' data-dismiss='modal'>&times;</button>
            </div>

            <div class="modal-body">
                <form action="" method='POST' enctype='multipart/form-data'>
                    {{ form.as_p }}
                    {% csrf_token %}
                    <button type="submit" >Post</button>
                </form>
            </div>

            <div class="modal-footer">
                <button type='button' data-dismiss='modal' class="btn btn-danger">Close</button>
            </div>
        </div>
    </div>
</div>
<br>
<div class="row">
    {% for post in user.post.all %}
        <div class="crop">
            <img src="/media/{{post.image}}" alt="" title='{{post.caption}}'>
        </div>
    {% endfor %}
</div>
{% endblock body_block %}

templates/login/user_other.html
{% extends 'navbar.html' %}

{% block title_block %}
{{ user_other.user_profile.full_name }} (@{{user_other.username}})
{% endblock title_block %}

{% block css_block %}
<style>
    .crop{
        margin-top: 20px;
        width: 200px;
        height: 200px;
        overflow: hidden;
    }
    .crop img{
        width: 400px;
        height: 300px;
        margin: -75px 0 0 -100px;
    }
</style>
{% endblock css_block %}

{% block body_block %}
<div class="row">
    <div class="col-sm-4">
        {% if user_other.user_profile.profile_pic %}
            <img
                src="/media/{{ user.user_profile.profile_pic }}"
                alt=""
                class="rounded-circle"
                width="150px"
                height="150px"
            />
        {% else %}
            <img
                src="/media/default.png"
                alt=""
                class="rounded-circle"
                width="150px"
                height="150px"
            />
        {% endif %}
    </div>
    <div class="col-sm-8">
        <h3>{{ user_other.username }} &nbsp; 
        
        {% if not already_followed %}
            <a href="{% url 'login:follow' username=user_other.username %}" class='btn btn-primary btn-sm'>Follow</a> 
        {% else %}
            <a href="{% url 'login:unfollow' username=user_other.username %}" class='btn btn-primary btn-sm'>Unfollow</a> 
        {% endif %}
            
        </h3>
        <br>
        <h4>{{ user_other.post.count }} posts &nbsp; &nbsp; 
            {{ user_other.following.count }} followers &nbsp; &nbsp; 
            {{ user_other.follower.count }} following
        </h4>
        <br>
        <h3>{{ user_other.user_profile.full_name }}</h3>
        <h6>{{ user_other.user_profile.description|linebreaks }}</h6>
    </div>
</div>

<div class="row">
    {% for post in user_other.post.all %}
        <div class="crop">
            <img src="/media/{{post.image}}" alt="" title='{{post.caption}}'>
        </div>
    {% endfor %}
</div>
{% endblock body_block %}